// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxLZ-_FI2vU4udGyHdq43NMn1PlQmv8go',
    appId: '1:179395750037:web:c220a94c5f2d96848c139c',
    messagingSenderId: '179395750037',
    projectId: 'grimoireproject-536d3',
    authDomain: 'grimoireproject-536d3.firebaseapp.com',
    storageBucket: 'grimoireproject-536d3.firebasestorage.app',
    measurementId: 'G-NXY3K9B9NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGTGr1DGX_W0KrNXjKmppCe7a3Mkg-95U',
    appId: '1:179395750037:android:0c59ffa8c2efb6558c139c',
    messagingSenderId: '179395750037',
    projectId: 'grimoireproject-536d3',
    storageBucket: 'grimoireproject-536d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuj9yxW_98lur2bvoqZdJBW___iu07ll4',
    appId: '1:179395750037:ios:d46ecea2ad6703e38c139c',
    messagingSenderId: '179395750037',
    projectId: 'grimoireproject-536d3',
    storageBucket: 'grimoireproject-536d3.firebasestorage.app',
    iosBundleId: 'com.example.flutterGrimoire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuj9yxW_98lur2bvoqZdJBW___iu07ll4',
    appId: '1:179395750037:ios:d46ecea2ad6703e38c139c',
    messagingSenderId: '179395750037',
    projectId: 'grimoireproject-536d3',
    storageBucket: 'grimoireproject-536d3.firebasestorage.app',
    iosBundleId: 'com.example.flutterGrimoire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxLZ-_FI2vU4udGyHdq43NMn1PlQmv8go',
    appId: '1:179395750037:web:e14f538e328507aa8c139c',
    messagingSenderId: '179395750037',
    projectId: 'grimoireproject-536d3',
    authDomain: 'grimoireproject-536d3.firebaseapp.com',
    storageBucket: 'grimoireproject-536d3.firebasestorage.app',
    measurementId: 'G-XBPFV50XQP',
  );
}
